name: Terraform CI/CD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check
    
    - name: Terraform Workspace Select
      run: terraform workspace select dev

    - name: Terraform Validade
      run: terraform validate
    
    - name: Terraform Plan
      run: terraform plan
  
  prod:
    runs-on: ubuntu-latest
    needs: dev
    if: github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest
      
      - name: Terraform Init
        run: terraform init
  
      - name: Terraform Format
        run: terraform fmt -check
      
      - name: Terraform Workspace Select
        run: terraform workspace select prod
  
      - name: Terraform Validade
        run:  terraform validate
      
      - name: Terraform Plan
        run: terraform plan
